---
AWSTemplateFormatVersion: '2010-09-09'
Description: Provides a template to enable security services and logging to a given VPC.
Parameters:
  VPCProduction:
    Description: ID of the Production VPC where the SFTPServer will be deployed.
    Type: AWS::EC2::VPC::Id
Resources:
  CloudTrailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 'CloudTrail-${AWS::Region}-${AWS::AccountId}'
      RetentionInDays: 400
  CloudWatchTrailLogRole:
    Type: AWS::IAM::Role
    DependsOn: CloudTrailLogGroup
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: FlowLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Resource: !GetAtt CloudTrailLogGroup.Arn
  CloudTrailS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      BucketName: !Sub 'cloudtrail-${AWS::Region}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  CloudTrailS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    DependsOn: CloudTrailS3Bucket
    Properties:
      Bucket: !Ref CloudTrailS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AWSCloudTrailAclCheck
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 's3:GetBucketAcl'
          Resource: !GetAtt CloudTrailS3Bucket.Arn
        - Sid: AWSCloudTrailWrite
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 's3:PutObject'
          Resource: !Sub 'arn:aws:s3:::${CloudTrailS3Bucket}/AWSLogs/${AWS::AccountId}/*'
  CloudTrailProd:
    Type: 'AWS::CloudTrail::Trail'
    DependsOn:
      - CloudTrailLogGroup
      - CloudWatchTrailLogRole
      - CloudTrailS3Bucket
      - CloudTrailS3BucketPolicy
    Properties:
      TrailName: !Sub 'CloudTrail-${AWS::Region}'
      CloudWatchLogsLogGroupArn: !GetAtt CloudTrailLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt CloudWatchTrailLogRole.Arn
      S3BucketName: !Ref CloudTrailS3Bucket
      EnableLogFileValidation: true
      IsLogging: true
      IsMultiRegionTrail: false
      IncludeGlobalServiceEvents: true
  GuardDuty:
    Type: 'AWS::GuardDuty::Detector'
    Properties:
      Enable: true
  # ConfigS3Bucket:
  #   Type: 'AWS::S3::Bucket'
  #   DeletionPolicy: Delete
  #   Properties:
  #     AccessControl: Private
  #     BucketName: !Sub 'config-${AWS::Region}-${AWS::AccountId}'
  #     BucketEncryption:
  #       ServerSideEncryptionConfiguration:
  #         - ServerSideEncryptionByDefault:
  #             SSEAlgorithm: AES256
  #     PublicAccessBlockConfiguration:
  #       BlockPublicAcls: true
  #       BlockPublicPolicy: true
  #       IgnorePublicAcls: true
  #       RestrictPublicBuckets: true
  # ConfigRecorder:
  #   Type: 'AWS::Config::ConfigurationRecorder'
  #   Properties:
  #     Name: !Sub 'sftp-${AWS::Region}-${AWS::AccountId}'
  #     RoleARN: !GetAtt XXXXXXXXX.Arn
  # ConfigDeliveryChannel:
  #   Type: 'AWS::Config::DeliveryChannel'
  #   Properties:
  #     ConfigSnapshotDeliveryProperties:
  #       DeliveryFrequency: Six_Hours
  #     S3BucketName: !Ref ConfigS3Bucket
  SecurityHub:
    Type: 'AWS::SecurityHub::Hub'
    Properties:
      Tags:
        Environment: Production
Outputs:
  CloudTrail:
    Value: !Ref CloudTrailProd
  CloudTrailLogGroupID:
    Value: !Ref CloudTrailLogGroup
  CloudTrailBucket:
    Value: !Ref CloudTrailS3BucketPolicy
  SecurityHubArn:
    Value: !Ref SecurityHub
...
