---
AWSTemplateFormatVersion: '2010-09-09'
Description: A basic template to enable security services to a given VPC.
Parameters:
  VPCProduction:
    Description: ID of the Production VPC where the SFTPServer will be deployed.
    Type: AWS::EC2::VPC::Id
Resources:
  CloudWatchTrailLogRole:
    Description: IAM role used by VPC to log data to CloudWatch
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: FlowLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Resource: "*"
  CloudTrailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 'CloudTrail-${AWS::Region}-${AWS::AccountId}'
      RetentionInDays: 400
  CloudTrailProd:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: !Sub 'CloudTrailProd-${AWS::Region}'
      CloudWatchLogsLogGroupArn: !GetAtt CloudTrailLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt CloudWatchTrailLogRole.Arn
      EnableLogFileValidation: true
      IsLogging: true
      IsMultiRegionTrail: false
      IncludeGlobalServiceEvents: true
Outputs:
  CloudTrailID:
    Value: !Ref CloudTrailProd
  CloudTrailLogGroupID:
      Value: !Ref CloudTrailLogGroup
